[server]
listen_address = "0.0.0.0:4144"
allowed_login_methods = ["recurse_center"]
tls_identity_file = "/media/persistent/certbot/live/tozt.net/identity.pfx"
uid = "teleterm"
gid = "teleterm"

[oauth.recurse_center]
client_id = "<%= @client_id %>"
client_secret = "<%= @client_secret %>"
